# .github/workflows/pipreqs.yml
name: Generate and PR Requirements

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pipreqs
          sudo apt-get install -y git
          sudo apt-get install -y gh

      - name: Generate requirements.txt
        run: pipreqs --force .

      - name: Check for changes
        id: check_changes
        run: |
          git add requirements.txt
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "::group::requirements.txt diff"
            git diff --cached requirements.txt
            echo "::endgroup::"
          fi
        shell: bash

      - name: Create PR if requirements.txt changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          BRANCH="update-requirements-$(date +%s)"
          git checkout -b "$BRANCH"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: update requirements.txt via pipreqs"
          git push origin "$BRANCH"

          gh pr create \
            --title "chore: update requirements.txt" \
            --body "Auto-generated via pipreqs in GitHub Actions" \
            --head "$BRANCH" \
            --base main
            --label "patch"
