name: Sync wiki to GitHub Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'

jobs:
  push-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone wiki repo
        run: |
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki_repo
          rsync -av --delete ./wiki/ ./wiki_repo/
          cd wiki_repo
          git add .
          git diff --cached --quiet || git commit -m "Automated sync from ./wiki folder"
          git push
